spring:
  application:
    name: element-binder

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      schema: element_binder_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS element_binder_schema
      connection-timeout: 10000

  liquibase:
    default-schema: element_binder_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  key: ${JWT_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

minio:
  endpoint: "http://minio:9000"
  access-key: "minio"
  secret-key: "minio_password"
  images-bucket-name: "images"